On successful registration, users should receive a JWT
andela/mervels-bn-backend pull request #16
Opened 2019-09-09 14:31 UTC by j0flintking02

#### What does this PR do?
implement user registration
#### Description of Task to be completed?
- add user signup functionality
- add dependencies to the package.json
- add test for the functionality
- fixes the testing script
- fixes the env import error
#### How should this be manually tested?
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[]()
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-09-09 18:13 UTC, Bahatiroben requested changes

2019-09-09 18:13 UTC, Bahatiroben commented on src/services/userService.js
> +  static async createUser(user) {
It will be better if we don't static methods in controllers

2019-09-09 19:13 UTC, Bahatiroben approved these changes
LOOKS GOOD FOR NOW

2019-09-10 06:32 UTC, willywax approved these changes
Looks good

2019-09-10 11:03 UTC, Paulvitalis200 approved these changes

2019-09-10 11:05 UTC, merged