feat(user-role-settings): implement user role update
andela/mervels-bn-backend pull request #25
Opened 2019-09-17 11:31 UTC by j0flintking02

#### What does this PR do?
Implement the user role update by the super administrator
#### Description of Task to be completed?
- ensure only super admin can update the user roles
- implement the swagger documentation for the feature
- implement error handling for failed delivery
#### How should this be manually tested?
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168131425](https://www.pivotaltracker.com/story/show/168131425)
#### Screenshots (if appropriate)
<img width="1158" alt="Screen Shot 2019-09-17 at 13 29 29" src="https://user-images.githubusercontent.com/26383328/65038026-4385d980-d94f-11e9-8068-f1090fb1d102.png">

2019-09-18 05:54 UTC, Dkabiswa commented
hei can you add the route we have to visit and sample data under 
#### how to test this manually

2019-09-18 07:19 UTC, j0flintking02 commented
> * You add the route we have to visit and sample data under "how to test this manually"
> * Since the password in the seeds is a hash can you find a way of sharing the real passwords to be used during testing.
> * Also, add a badge of either ready to review or WIP

I have made these changes

2019-09-18 14:11 UTC, drayzii requested changes

2019-09-18 14:11 UTC, drayzii commented on src/routes/api/users.js
> +router.put('/updateRole', userValidator.validateUserRole, Access.isAdmin, Users.updateUserRole);
Since the first middleware decodes the token, can't you remove the part you decode it in the second and access it through `req.user`

2019-09-18 14:28 UTC, drayzii commented
There is also an issue of updating a user to a role he/she already has. I just re-updates it. Could you add the check

2019-09-18 16:13 UTC, drayzii approved these changes
LGTM

2019-09-19 07:40 UTC, willywax requested changes
Every thing looks great. Just somethings to look for
- Super Admin can update his/her own role. This can lead to not having a Super Administrator
- Not encoding roles in token. This causes an issue when a logged In user's role is updated.
- There's a typo in the response message when a manager is changed. It reads `the new manage role ...`

2019-09-19 13:49 UTC, willywax approved these changes
Look good

2019-09-19 21:08 UTC, merged

2019-09-19 21:08 UTC, Paulvitalis200 approved these changes