#168131444 Users should be able to provide feedback
andela/mervels-bn-backend pull request #43
Opened 2019-09-27 06:38 UTC by j0flintking02

#### What does this PR do?
Implement feedback for accommodations
#### Description of Task to be completed?
- Users should be able to view the feedback from the other users
- Arrange the request in descending order
- Users should be able to comment/provide feedback about an accommodation facility.
- implement error handling for failed delivery
#### How should this be manually tested?
- clone the repo and checkout to this branch `ft-feedback-168131444`
- delete the current tables in the database
- Then run migrations
- Run seeds to add more data into the database `sequelize db:seed: all`
- Run `npm run start:dev`
- head over to postman and use the route:`localhost:3000/api/v1/auth/signin`
-  Ensure that you are logged in and obtain the token
```json
{
    "userEmail": "jonashyaka2@gmail.com",
    "userPassword": "Root1234@"
}
```
- copy the token that will be used to access the updateRole route
- then use the route:`localhost:3000/api/v1/accommodations/1/feedback`
```json
{
  "feedback": "Please clarify the travel reason"
}
```
- Feedback can be viewed from the single accommodation route `/api/v1/accommodations/1`
- To run the test `run npm test`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168131444](https://www.pivotaltracker.com/story/show/168131444)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-09-27 at 08 14 21" src="https://user-images.githubusercontent.com/26383328/65746322-e2a09300-e0fe-11e9-8fb2-c469314f7ba4.png">
<img width="1440" alt="Screen Shot 2019-09-27 at 08 16 28" src="https://user-images.githubusercontent.com/26383328/65746462-38753b00-e0ff-11e9-88a8-f33b8062890e.png">

#### Questions:
N/A

2019-09-27 10:58 UTC, drayzii requested changes

2019-09-27 10:58 UTC, drayzii commented on src/controllers/accommodationController.js
> +      const feedbacks = await FeedbackService.getFeedbackById(accommodationId);
I believe we should use associations here

2019-09-27 11:59 UTC, Bahatiroben approved these changes
add the functionality to check whether the accommodation exist before storing the feedback

2019-09-30 12:47 UTC, Paulvitalis200 approved these changes

2019-09-30 12:49 UTC, merged